//! The object dictionary: every index a node serves over SDO, and what each one means.
//!
//! This module is the source of truth for the config plane. `device-conf/can-io.toml` restates
//! the same table in the form `zencan-build` can parse (name, data type, array size, default) and
//! carries a one-line summary per object; the reasoning, the units, the coded values and the
//! ordering rules live here.
//!
//! # The three blocks
//!
//! - **0x1000 — identity and housekeeping.** Generated by `zencan-build` from the device config's
//!   top-level keys rather than declared object by object. Not persisted.
//! - **0x2000 — process data.** Read-only unless noted, never persisted. This is the same state
//!   the TPDOs broadcast, reachable one object at a time for a master that wants to poll rather
//!   than listen.
//! - **0x3000 — configuration.** Read/write, and persisted to NOR on request (see
//!   [`SIGNATURE_SAVE`]). A board's compile-time per-node constants are *factory defaults only*: a
//!   board with a valid stored config ignores them.
//!
//! # Sentinels
//!
//! Three values mean "nothing here" and are worth knowing before reading anything else:
//! [`RAW_INVALID`] for a raw ADC slot that did not answer, [`SENSOR_INVALID`] for a calibrated
//! slot with no usable reading, and [`NO_INDEX`] for an unset optional index in the config block.
//! None of them can be confused with a real value: a sensor cannot legitimately read `i16::MIN`,
//! and no index domain on this board reaches 255.

/// A raw ADC slot that did not answer during the last I2C sweep (0x2000, 0x2001, 0x2006).
pub const RAW_INVALID: u16 = u16::MAX;

/// A sensor slot with no usable reading (0x2004, and every TPDO sensor channel).
///
/// Also what an unclaimed TPDO channel carries, so a listener needs no separate encoding for
/// "no slot is mapped here" versus "the slot mapped here has nothing to say".
pub const SENSOR_INVALID: i16 = i16::MIN;

/// The "unset" sentinel for an optional index in the 0x3000 block: no sensor slot, no valve, no
/// TPDO channel.
///
/// The one exception is an HCO reference (0x3011, 0x3012), whose wire form is 1-indexed so that
/// plain `0` can mean "none" — an output number in a wiring diagram is 1..=4 anyway.
pub const NO_INDEX: u8 = 0xFF;

/// Magic values for 0x1010 / 0x1011, as CANopen defines them: ASCII, little-endian.
pub const SIGNATURE_SAVE: u32 = 0x6576_6173; // "save"
/// See [`SIGNATURE_SAVE`].
pub const SIGNATURE_LOAD: u32 = 0x6461_6F6C; // "load"

// ===========================================================================
// 0x1000 — identity and housekeeping
// ===========================================================================

/// Store parameters. `uint32`, sub 1, read/write.
///
/// Writing [`SIGNATURE_SAVE`] commits the whole 0x3000 block to the on-board NOR flash. Nothing
/// in 0x1000 or 0x2000 is persisted, so a save captures configuration only — never process data.
pub const STORE_PARAMETERS: u16 = 0x1010;

/// Restore defaults. `uint32`, sub 1, read/write.
///
/// Writing [`SIGNATURE_LOAD`] erases the stored config and reverts to the compile-time factory
/// defaults for that node. It takes effect immediately, not at the next boot.
pub const RESTORE_DEFAULTS: u16 = 0x1011;

/// Producer heartbeat period in milliseconds, 0 to stop announcing. `uint16`, read/write.
///
/// This is the node's *own* liveness on `0x700 + node_id`. What it does when the *master* goes
/// quiet is a separate mechanism entirely — see [`FALLBACK_A_MS`].
pub const HEARTBEAT_PERIOD: u16 = 0x1017;

// ===========================================================================
// 0x2000 — process data. Read-only unless noted; never persisted.
// ===========================================================================

/// Raw ADC101C027 conversion results on I2C bus 0. `uint16[9]`, read-only.
///
/// Indexed by position in the board's amplifier address table, **not** by I2C address, so a board
/// strapped to the wrong address shows up as a reading in the wrong entry rather than as a
/// plausible one. An address that did not answer during the last sweep reads [`RAW_INVALID`].
pub const RAW_ADC_BUS0: u16 = 0x2000;

/// Raw ADC101C027 conversion results on I2C bus 1. `uint16[9]`, read-only. See [`RAW_ADC_BUS0`].
pub const RAW_ADC_BUS1: u16 = 0x2001;

/// I2C device presence bitmap, one entry per bus. `uint16[2]`, read-only.
///
/// This is the assembly-verification view — what is physically answering, before any
/// interpretation:
///
/// | bit    | meaning                                                        |
/// |--------|----------------------------------------------------------------|
/// | 0..=8  | amplifier *n* in the address table acknowledged                 |
/// | 9      | this bus's AS5600 magnetic encoder answered                     |
/// | 10     | that encoder reports a magnet at a usable distance              |
///
/// Bit 10 is separate from bit 9 on purpose: an encoder whose magnet has drifted too far or too
/// close still returns an angle, and that angle is wrong. Folding it into presence would make a
/// mechanically broken installation look healthy.
pub const I2C_PRESENT: u16 = 0x2002;

/// Completed I2C presence sweeps since boot. `uint32`, read-only.
///
/// Increments once per full sweep of both buses, so a stale [`I2C_PRESENT`] bitmap is visible as
/// a frozen counter rather than as data that merely looks plausible.
pub const I2C_SWEEPS: u16 = 0x2003;

/// Calibrated sensor readings, one per slot. `int16[16]`, read-only.
///
/// The value is a signed count of the unit named by the matching entry in [`SENSOR_UNIT`];
/// [`SENSOR_INVALID`] means no reading.
///
/// This is the complete picture. There are more slots than there are TPDO sensor channels, so
/// the `Sensor0`/`Sensor1`/`Sensor3` frames are a *selection* from this array — see
/// [`SENSOR_PDO_CHANNEL`].
pub const SENSOR_VALUE: u16 = 0x2004;

/// The unit each sensor slot reports in. `uint8[16]`, read-only.
///
/// | code | unit                    |
/// |------|-------------------------|
/// | 0    | centibar                |
/// | 1    | decibar                 |
/// | 2    | centidegrees Celsius    |
/// | 3    | raw device counts       |
/// | 4    | promille                |
///
/// Mirrors [`SENSOR_UNIT_CFG`] so a master can decode [`SENSOR_VALUE`] without reading the
/// configuration block at all. Decibar exists because a 400 bar transducer overflows an `i16` of
/// centibar; promille is what a magnetic encoder reports, in the same unit a valve position uses.
pub const SENSOR_UNIT: u16 = 0x2005;

/// Raw AS5600 angle per I2C bus, 0..=4095 over a full turn. `uint16[2]`, read-only.
///
/// [`RAW_INVALID`] when no encoder answered. The encoder's address is fixed at 0x36, so there is
/// at most one per bus and the bus index is its whole identity.
///
/// This is the *uncalibrated* reading, and it is what commissioning an angle slot runs on: park
/// the valve on each stop, read the number here, and derive the [`SENSOR_OFFSET`] /
/// [`SENSOR_SLOPE`] pair from the two. Setting the slot's unit to raw counts shows the same
/// number at [`SENSOR_VALUE`].
pub const RAW_ENCODER: u16 = 0x2006;

// --- valves: the three-layer state -----------------------------------------

/// What the master asked for, as a position word. `uint16[4]`, **read/write**.
///
/// The only writable process object. See [`crate::valve`] for the word's layout and for why a
/// position is range-checked on every write.
pub const VALVE_COMMANDED: u16 = 0x2010;

/// What the node actually aims for, as a position word. `uint16[4]`, read-only.
///
/// [`VALVE_COMMANDED`] clamped to [`VALVE_MIN_PROMILLE`]/[`VALVE_MAX_PROMILLE`], or overridden by
/// a heartbeat fallback stage, an operator-driven shutdown, or overpressure relief. The gap
/// between this and the commanded layer is exactly "what the node decided to do instead".
pub const VALVE_TARGET: u16 = 0x2011;

/// Where the node believes the valve actually is, as a position word. `uint16[4]`, read-only.
///
/// Integrated from the target, elapsed time and the configured travel time
/// ([`VALVE_TRAVEL_MS`]) — or read straight off the position sensor named by
/// [`VALVE_POSITION_SENSOR`] when one is fitted and reporting. The estimate is frozen while
/// unpowered or stalled, and the unpowered flag is set while nothing is holding the valve, which
/// is what makes this layer meaningful even with the drive released.
pub const VALVE_MEASURED: u16 = 0x2012;

/// Per-valve status code. `uint8[4]`, read-only.
///
/// | code | meaning                                                                 |
/// |------|-------------------------------------------------------------------------|
/// | 0    | unmapped — no valve configured on this index                            |
/// | 1    | unpowered — deliberately released; the position is the last estimate     |
/// | 2    | moving — travelling toward target                                       |
/// | 3    | holding — at target and being held                                      |
/// | 4    | stalled — over [`VALVE_STALL_MA`] for longer than [`VALVE_STALL_MS`]    |
pub const VALVE_STATUS: u16 = 0x2013;

/// Rail current attributed to each valve, milliamps. `uint16[4]`, read-only.
///
/// Feeds stall detection. HCO1+2 share one shunt and HCO3+4 share another, so this figure is only
/// unambiguous when a valve owns a whole HCO pair — which is how the servo wiring is laid out.
pub const VALVE_CURRENT: u16 = 0x2014;

/// State of the overpressure relief loop. `uint8`, read-only.
///
/// | code | meaning                                                              |
/// |------|----------------------------------------------------------------------|
/// | 0    | idle — watching, not intervening                                     |
/// | 1    | relieving — the valve is being held open                             |
/// | 2    | cooldown — letting the reading settle before re-arming               |
/// | 3    | inhibited — configured, but the watched slot has no valid reading     |
/// | 4    | disabled — not configured on this node                               |
///
/// See [`RELIEF_ENABLED`] for what the loop does and why `inhibited` does not vent.
pub const RELIEF_STATE: u16 = 0x2015;

/// Pulses each stepper has emitted since boot, direction-signed. `int32[2]`, **read/write**.
///
/// There is no home switch and the driver's own encoder is not wired back, so this count is
/// relative to power-on. Unlike [`VALVE_MEASURED`] it is **not** clamped into the configured
/// travel: reading it outside [`STEPPER_CLOSED_STEPS`]..[`STEPPER_OPEN_STEPS`] is how an actuator
/// that has walked off the end shows up.
///
/// Writing it is the only homing this actuator has: it declares the shaft to physically be at that
/// count **without moving it**. Drive the actuator to a known mechanical stop, then write the step
/// count for that stop. Rejected with `ResourceNotAvailable` on a node with no stepper configured.
pub const STEPPER_POSITION: u16 = 0x2016;

// --- direct high current output control ------------------------------------

/// Direct digital level per high current output. `uint8[4]`, **read/write**.
///
/// Writes are rejected with `CantStoreLocalControl` when the output is owned by a valve
/// ([`HCO_OWNER`]), unless raw debug mode ([`RAW_DEBUG_MODE`]) is active. Two things driving one
/// output is not a state this firmware is willing to be in by accident.
pub const HCO_DIGITAL: u16 = 0x2020;

/// Direct PWM pulse width per high current output, microseconds. `uint16[4]`, **read/write**.
/// Same ownership rules as [`HCO_DIGITAL`].
pub const HCO_PWM_US: u16 = 0x2021;

/// Who owns each high current output. `uint8[4]`, read-only.
///
/// 0 = free for direct control, *n* = driven by valve *n - 1*. One-indexed so that 0 can mean
/// "unowned".
pub const HCO_OWNER: u16 = 0x2022;

// --- board state -----------------------------------------------------------

/// Debug LED bitmask: bit 0 red, bit 1 yellow, bit 2 white. `uint8`, **read/write**.
pub const LEDS: u16 = 0x2030;

/// Bench mode. `uint8`, **read/write**. Volatile: not persisted, and cleared by any reset.
///
/// While set:
/// - HCO arbitration becomes last-writer-wins, so a valve-owned output can be driven directly for
///   servo testing;
/// - the heartbeat fallback state machine is suspended, so an unattended board on the assembly
///   bench does not drive its valves open after five minutes;
/// - the red LED is held on, because a board in this mode must be identifiable across a room.
///
/// Entered by writing 1 here, or by pressing the on-board button.
pub const RAW_DEBUG_MODE: u16 = 0x2031;

/// How the node currently sees the master. `uint8`, read-only.
///
/// | code | meaning                                                                    |
/// |------|----------------------------------------------------------------------------|
/// | 0    | never seen a master since boot                                             |
/// | 1    | alive                                                                      |
/// | 2    | fallback stage A                                                           |
/// | 3    | fallback stage B                                                           |
/// | 4    | suspended, because raw debug mode is active                                |
///
/// The fallback timers run from boot, so a node that never hears a master ends up in the same
/// safe state as one that lost it.
pub const LINK_STATE: u16 = 0x2032;

/// Milliseconds since the last master heartbeat. `uint32`, read-only.
pub const MS_SINCE_HEARTBEAT: u16 = 0x2033;

/// Rail currents in milliamps: logic, HCO1+2, HCO3+4. `uint16[3]`, read-only.
///
/// rev3 only; reads 0 on rev2, which has no on-board sensing — which is also why stall detection
/// has to be switched off there ([`VALVE_STALL_MA`]).
pub const RAIL_CURRENT: u16 = 0x2040;

/// Rail voltages in millivolts: logic, HCO1+2, HCO3+4. `uint16[3]`, read-only. rev3 only.
pub const RAIL_VOLTAGE: u16 = 0x2041;

/// Error counters, one per failure kind. `uint32[NUM_ERROR_COUNTERS]`, read-only.
///
/// Sub-index *n + 1* is the counter named by [`ErrorCounter`] with discriminant *n*. Everything
/// here is a hardware fault, a wiring fault or a firmware bug; nothing that happens in normal
/// operation is counted.
///
/// # How to read them
///
/// Free-running, monotonic, and they wrap at `u32`. Poll periodically and look at the
/// *difference* between reads: an absolute value means nothing without knowing the node's uptime,
/// and a wrap is just another difference. Only a reset of the board clears them, which makes an
/// unexpected return to zero its own signal — the node rebooted between your two reads.
///
/// Most count discrete events; a few count *samples*, climbing once per tick for as long as a
/// condition holds. [`ErrorCounter`] says which is which, and the distinction matters: an event
/// counter answers "how often did this happen", a sample counter answers "is it happening now".
pub const ERROR_COUNTERS: u16 = 0x2050;

/// Number of counters at [`ERROR_COUNTERS`], and the array size of that object.
pub const NUM_ERROR_COUNTERS: usize = 22;

/// What each sub-index of [`ERROR_COUNTERS`] counts.
///
/// The discriminant is the sub-index minus one, so **this list is append-only**: inserting a
/// variant renumbers every counter after it and silently changes what a master is trending.
/// Retiring one leaves a hole rather than removing the variant.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[repr(u8)]
pub enum ErrorCounter {
    /// An I2C transfer did not complete inside its timeout — a held SDA, a missing pull-up, or a
    /// device stretching the clock forever. Not a NACK.
    I2cTimeout = 0,
    /// The I2C peripheral reported arbitration loss, a bus error or an overrun.
    I2cBusError = 1,
    /// A device believed present did not acknowledge. Never the normal NACK from an empty
    /// address, which is not counted at all.
    I2cNack = 2,
    /// A device that had been answering stopped, and was dropped from [`I2C_PRESENT`]. One count
    /// per disappearance, not per failed read.
    I2cDeviceLost = 3,
    /// A read of an ADC101C027 believed present came back empty.
    AmplifierReadFailed = 4,
    /// An amplifier raised its own ALERT flag: its window comparator tripped.
    AmplifierAlert = 5,
    /// A read of an AS5600 believed present came back empty.
    EncoderReadFailed = 6,
    /// An AS5600's magnet went missing or out of range. The part still answers, and the angle it
    /// answers with is wrong — so this is the only warning that a position reading is a lie.
    EncoderMagnetLost = 7,
    /// **Sample counter.** A configured sensor slot was sampled while its device was absent.
    /// Nonzero from boot, with nothing having disappeared, is the signature of a sensor
    /// configured onto a bus or address it is not wired to.
    SensorSourceMissing = 8,
    /// The bxCAN receive FIFO overran: frames were dropped by the peripheral before software saw
    /// them.
    CanRxOverrun = 9,
    /// The CAN receiver returned an error — a bus fault, or a malformed frame.
    CanRxError = 10,
    /// The node's internal fan-out lagged and a task missed frames that did arrive. Incremented
    /// by the number of messages lost. Distinct from [`Self::CanRxOverrun`]: that is the hardware
    /// giving up, this is a task not keeping up.
    CanRxDropped = 11,
    /// A frame waiting in a transmit mailbox was evicted before it went out. Nothing retries it.
    CanTxDropped = 12,
    /// The node tried to transmit something that is not a legal frame. Always a firmware bug.
    CanTxInvalid = 13,
    /// An SDO request could not be decoded, or asked for a transfer type this server does not
    /// implement (anything but expedited).
    SdoRequestInvalid = 14,
    /// An SDO write was refused with an abort code. Usually a master with a stale idea of this
    /// node's dictionary.
    SdoWriteRejected = 15,
    /// An SDO response did not fit in a frame and was dropped, leaving the master waiting. A
    /// firmware bug — every object here is expedited-sized.
    SdoResponseDropped = 16,
    /// A valve latched a stall ([`VALVE_STALL_MA`]). One count per stall, not per tick spent
    /// stalled.
    ValveStall = 17,
    /// Relief was armed but its watched slot had no valid reading, so it could not act. See
    /// [`RELIEF_ENABLED`] for why that inhibits rather than vents.
    ReliefInhibited = 18,
    /// A read, erase or write of the config NOR flash failed, including at boot when the part did
    /// not identify itself.
    ConfigFlashError = 19,
    /// A config failed its sanity check — one read back from flash, or one a master asked to
    /// persist. Neither is applied.
    ConfigInvalid = 20,
    /// The watchdog pet ran measurably late: something blocked the executor.
    ///
    /// This is the near miss, and deliberately the only counter about the executor. A watchdog
    /// reset, a panic and a HardFault all end in a reset that clears every counter here, so none
    /// of them can be counted in RAM — catching those needs a region the reset does not touch,
    /// which this object does not have.
    WatchdogLate = 21,
}

impl ErrorCounter {
    /// All of them, in sub-index order.
    pub const ALL: [Self; NUM_ERROR_COUNTERS] = [
        Self::I2cTimeout,
        Self::I2cBusError,
        Self::I2cNack,
        Self::I2cDeviceLost,
        Self::AmplifierReadFailed,
        Self::AmplifierAlert,
        Self::EncoderReadFailed,
        Self::EncoderMagnetLost,
        Self::SensorSourceMissing,
        Self::CanRxOverrun,
        Self::CanRxError,
        Self::CanRxDropped,
        Self::CanTxDropped,
        Self::CanTxInvalid,
        Self::SdoRequestInvalid,
        Self::SdoWriteRejected,
        Self::SdoResponseDropped,
        Self::ValveStall,
        Self::ReliefInhibited,
        Self::ConfigFlashError,
        Self::ConfigInvalid,
        Self::WatchdogLate,
    ];

    /// The counter at sub-index `sub` of [`ERROR_COUNTERS`], for decoding a captured read.
    pub const fn from_sub(sub: u8) -> Option<Self> {
        if sub == 0 || sub as usize > NUM_ERROR_COUNTERS {
            return None;
        }
        Some(Self::ALL[sub as usize - 1])
    }

    /// The sub-index this counter is read at.
    pub const fn sub(self) -> u8 {
        self as u8 + 1
    }
}

// ===========================================================================
// 0x3000 — configuration. Read/write, persisted on request.
// ===========================================================================

/// Node id of the master whose heartbeat this node listens for. `uint8`, read/write.
pub const MASTER_NODE_ID: u16 = 0x3000;

/// Fallback stage A timeout, milliseconds. `uint32`, read/write.
///
/// Stage A is the "lost the master, make the vehicle safe" state, entered this long after the
/// last master heartbeat. Short — a few seconds — because the point is to act before anything
/// downstream notices the master is gone.
pub const FALLBACK_A_MS: u16 = 0x3001;

/// Fallback stage B timeout, milliseconds. `uint32`, read/write.
///
/// Stage B is the "the master is not coming back" state: minutes, not seconds, and normally
/// configured to vent. Measured from the same last-heartbeat instant as stage A, not from the
/// stage A transition.
pub const FALLBACK_B_MS: u16 = 0x3002;

/// Valve positions to take in fallback stage A, promille. `uint16[4]`, read/write.
///
/// A plain promille: the unpowered flag is rejected here, since whether a stage releases its
/// servo is the separate [`FALLBACK_A_UNPOWER`] field.
pub const FALLBACK_A_POSITION: u16 = 0x3003;

/// Valve positions to take in fallback stage B, promille. `uint16[4]`, read/write.
/// See [`FALLBACK_A_POSITION`].
pub const FALLBACK_B_POSITION: u16 = 0x3004;

/// Drop the servo's power output after it reaches the stage A position. `uint8[4]`, read/write.
///
/// Applied once the position is reached *and* [`VALVE_SETTLE_MS`] has elapsed. Saves the battery
/// over a long outage; a ball valve holds its position mechanically, so releasing the drive costs
/// nothing.
pub const FALLBACK_A_UNPOWER: u16 = 0x3005;

/// Drop the servo's power output after it reaches the stage B position. `uint8[4]`, read/write.
/// See [`FALLBACK_A_UNPOWER`].
pub const FALLBACK_B_UNPOWER: u16 = 0x3006;

/// Master heartbeat fallback enabled. `uint8`, read/write.
///
/// Off is for a board on the bench that has no master to lose. A board in the vehicle with this
/// clear will sit on its last command indefinitely.
pub const FALLBACK_ENABLED: u16 = 0x3007;

// --- valve mapping and calibration -----------------------------------------

/// What kind of valve is on each index. `uint8[4]`, read/write.
///
/// 0 = not fitted, 1 = solenoid, 2 = servo, 3 = stepper. A solenoid is on or off; a servo takes a
/// PWM position and has a travel time, a settle time and optionally a separate power output. A
/// stepper is described at [`STEPPER_VALVE`].
pub const VALVE_KIND: u16 = 0x3010;

/// High current output supplying the valve's power, 1..=4, or 0 for none. `uint8[4]`, read/write.
///
/// "None" is the right answer for a solenoid, and for a servo that is permanently powered from
/// elsewhere — such a valve simply can never be unpowered.
pub const VALVE_POWER_HCO: u16 = 0x3011;

/// High current output carrying the valve's signal, 1..=4, or 0 for none. `uint8[4]`, read/write.
///
/// PWM for a servo, the coil itself for a solenoid.
pub const VALVE_SIGNAL_HCO: u16 = 0x3012;

/// Servo pulse width at fully closed, microseconds. `uint16[4]`, read/write.
///
/// May be larger than [`VALVE_OPEN_US`]; the firmware interpolates between the two in whichever
/// direction they are given, so a servo mounted backwards is a calibration entry rather than a
/// wiring change.
pub const VALVE_CLOSED_US: u16 = 0x3013;

/// Servo pulse width at fully open, microseconds. `uint16[4]`, read/write.
/// See [`VALVE_CLOSED_US`].
pub const VALVE_OPEN_US: u16 = 0x3014;

/// Time for a full 0 -> 1000 promille sweep, milliseconds. `uint16[4]`, read/write.
///
/// Drives the [`VALVE_MEASURED`] estimate and the settle deadline, so it is what "where is the
/// valve" means on a node with no position sensor. Measure it once per valve type on the bench.
pub const VALVE_TRAVEL_MS: u16 = 0x3015;

/// Rail current above which a moving valve is considered stalled, milliamps. `uint16[4]`,
/// read/write. 0 disables stall detection for that valve.
///
/// 0 is also the only workable setting on rev2, which has no on-board current sensing.
pub const VALVE_STALL_MA: u16 = 0x3016;

/// How long the current must stay over [`VALVE_STALL_MA`] before declaring a stall, milliseconds.
/// `uint16[4]`, read/write.
///
/// Debounce: a servo's inrush is not a stall.
pub const VALVE_STALL_MS: u16 = 0x3017;

/// How long after arriving before the valve is considered settled, milliseconds. `uint16[4]`,
/// read/write. Gates the fallback unpower decision.
pub const VALVE_SETTLE_MS: u16 = 0x3018;

/// Minimum commandable position, promille. `uint16[4]`, read/write.
///
/// The input clamp, and the whole of the difference between [`VALVE_COMMANDED`] and
/// [`VALVE_TARGET`] in normal operation: a valve that must never fully close gets a floor here,
/// enforced by the node rather than by every master that might command it.
pub const VALVE_MIN_PROMILLE: u16 = 0x3019;

/// Maximum commandable position, promille. `uint16[4]`, read/write. See [`VALVE_MIN_PROMILLE`].
pub const VALVE_MAX_PROMILLE: u16 = 0x301A;

/// Sensor slot reporting where this valve actually is, or [`NO_INDEX`] for no feedback.
/// `uint8[4]`, read/write.
///
/// Without one, [`VALVE_MEASURED`] is extrapolated from [`VALVE_TRAVEL_MS`] — it says where the
/// valve *should* be by now. A slot named here replaces that estimate with a reading, so it must
/// report promille; the node refuses a configuration where it does not, rather than driving a
/// valve against a pressure on the strength of a number in the wrong unit. In practice this
/// points at an angle slot.
///
/// If the sensor stops reporting, the valve silently reverts to the travel-time estimate rather
/// than freezing at its last reading.
pub const VALVE_POSITION_SENSOR: u16 = 0x301B;

// --- sensor mapping and calibration ----------------------------------------

/// Which I2C bus each sensor slot reads from: 0, 1, or [`NO_INDEX`] for an unused slot.
/// `uint8[16]`, read/write.
///
/// Together with [`SENSOR_KIND`] this is the whole of a slot's addressing. An angle slot is the
/// AS5600 on this bus — fixed address 0x36, so at most one per bus, and [`SENSOR_AMPLIFIER`] is
/// ignored. Every other kind is the amplifier named by [`SENSOR_AMPLIFIER`] on this bus.
pub const SENSOR_BUS: u16 = 0x3020;

/// Which amplifier on the slot's bus, as an index into the board's address table (0..=8) — not a
/// raw I2C address. `uint8[16]`, read/write.
///
/// Ignored for an angle slot, whose device has no address straps.
pub const SENSOR_AMPLIFIER: u16 = 0x3021;

/// What kind of sensor is in each slot. `uint8[16]`, read/write.
///
/// | code | sensor                                   |
/// |------|------------------------------------------|
/// | 0    | unused                                   |
/// | 1    | pressure transducer (linear)             |
/// | 2    | Pt1000 temperature                       |
/// | 3    | MCP9700 temperature (linear)             |
/// | 4    | AS5600 magnetic rotary encoder           |
///
/// The kind decides which device the slot is read from and how that device's raw number is
/// linearised. Everything after that is [`SENSOR_OFFSET`]..[`SENSOR_CONSTANT`].
///
/// # Write the kind first
///
/// Changing the kind re-seeds this slot's calibration and unit from the new kind, because the old
/// values described a different sensor — a slope in nanobar per count means nothing to a Pt1000.
/// Writing the same kind again is a no-op, so a master that resends its whole configuration will
/// not wipe the coefficients it just sent.
///
/// For kinds 2 and 3 the re-seeded calibration is complete and working: the Pt1000 bridge is the
/// board's own resistors and the MCP9700's curve is in its datasheet, so one write is enough to
/// get a real temperature. Kinds 1 and 4 have no honest default — a transducer's slope comes off
/// the bench and an encoder's from where its magnet ended up — so they are left uncalibrated and
/// report no reading (see [`SENSOR_SLOPE`]) until the coefficients arrive.
pub const SENSOR_KIND: u16 = 0x3022;

/// Calibration offset, in thousandths of the linearised input. `int32[16]`, read/write.
///
/// # The one calibration form
///
/// Every kind is calibrated the same way:
///
/// ```text
///   out = (linear - offset) * slope / 1e9 + constant
/// ```
///
/// where `linear` is the kind's raw number linearised to *thousandths* of the quantity being
/// calibrated, `out` is thousandths of the reported quantity, and the slot's unit
/// ([`SENSOR_UNIT_CFG`]) does the final scale down to what appears at [`SENSOR_VALUE`]. So this
/// object is in the same thousandths as `linear`, [`SENSOR_SLOPE`] is nano-output-units per
/// linear unit, and [`SENSOR_CONSTANT`] is thousandths of the output.
///
/// | kind      | `linear` is  | offset       | slope                    | constant       |
/// |-----------|--------------|--------------|--------------------------|----------------|
/// | pressure  | milli-counts | milli-counts | nanobar per count        | millibar       |
/// | MCP9700   | milli-counts | milli-counts | nanocelsius per count    | millicelsius   |
/// | Pt1000    | millicelsius | millicelsius | nanocelsius per mC, 1e9 = unity | millicelsius |
/// | angle     | milli-counts | milli-counts | see below                | milli-promille |
///
/// A transducer's bench calibration is recorded as `pressure_bar = (reading - offset) * factor`,
/// which is exactly this with `offset` in milli-counts and `factor` scaled to nanobar per count.
/// Set [`SENSOR_CONSTANT`] to 1013 for a transducer characterised against ambient that should
/// report absolute rather than gauge pressure — which convention a slot uses is then visible in
/// its own calibration instead of being implied by the firmware version.
///
/// For a Pt1000 the bridge inversion is fixed, since it is the board's resistors rather than the
/// probe, so a virgin slot is offset 0, slope 1e9, constant 0 and the three fields exist to trim
/// out amplifier offset and gain error against a known bath.
///
/// For an angle slot, park the valve on each stop, read the raw angle ([`RAW_ENCODER`]), then set
/// this to `closed_counts * 1000` and the slope to `1e9 / (open_counts - closed_counts)`. That
/// difference is **signed**: a valve whose angle decreases as it opens gets a negative slope,
/// which is also what tells the firmware which way round the turn the travel runs. The zeroing
/// wraps at a full turn, so a closed stop sitting across the encoder's own origin is fine.
pub const SENSOR_OFFSET: u16 = 0x3023;

/// Calibration slope, nano output units per linearised input unit. `int32[16]`, read/write.
/// See [`SENSOR_OFFSET`] for the form and the per-kind table.
///
/// # A slope of zero means uncalibrated
///
/// It does not mean "reads a constant". No real sensor maps every possible input onto one number,
/// so the slot reports [`SENSOR_INVALID`] rather than a confident, plausible, wrong value — a
/// transducer reading a steady 0.00 bar is far more dangerous than one admitting it does not
/// know. This is the state a pressure or angle slot is in between its kind being written and its
/// coefficients arriving.
///
/// Raw device counts (unit code 3) are exempt: that unit bypasses the calibration entirely, which
/// is what makes it possible to read the numbers you need in order to stop being uncalibrated.
pub const SENSOR_SLOPE: u16 = 0x3024;

/// The unit each slot reports in. `uint8[16]`, read/write. Mirrored read-only into
/// [`SENSOR_UNIT`], where the code table is.
pub const SENSOR_UNIT_CFG: u16 = 0x3025;

/// Calibration constant term, thousandths of the output unit. `int32[16]`, read/write.
///
/// Zero for the plain `(reading - offset) * slope` form; 1013 to report absolute pressure from a
/// transducer calibrated against ambient. See [`SENSOR_OFFSET`].
pub const SENSOR_CONSTANT: u16 = 0x3026;

/// Which TPDO sensor channel broadcasts this slot, or [`NO_INDEX`] for a slot that is never
/// broadcast. `uint8[16]`, read/write.
///
/// There are more slots than channels ([`crate::NUM_PROTOCOL_SENSOR_SLOTS`]), so this is a real
/// choice rather than an index. A slot with no channel is still sampled, calibrated and readable
/// at [`SENSOR_VALUE`] — it just never appears in the `Sensor0`/`Sensor1`/`Sensor3` frames. Two
/// slots may not claim the same channel; the node refuses such a configuration rather than
/// letting one of them silently win.
///
/// Unset for every slot on a node with nothing configured. A node's factory defaults then give
/// each sensor they *do* fit in the first channels the matching channel *n*, which is what those
/// slots have always done, and the rest stay unbroadcast.
pub const SENSOR_PDO_CHANNEL: u16 = 0x3027;

/// Sensor sample interval, milliseconds. `uint16`, read/write.
pub const SENSOR_INTERVAL_MS: u16 = 0x3030;

/// I2C presence probe interval, milliseconds. `uint16`, read/write.
///
/// One address is probed per interval, so a full sweep of both buses takes as many intervals as
/// there are addresses. Probing is interleaved with normal reads specifically so that hunting for
/// newly plugged-in amplifier boards does not disturb the sample rate during assembly.
pub const SCAN_INTERVAL_MS: u16 = 0x3031;

/// TPDO broadcast period per kind, milliseconds. `uint16[18]`, read/write.
///
/// Sub-index *n + 1* is the period for TPDO kind *n* (see [`crate::TpdoKind`], whose discriminant
/// is that same *n*); 0 disables that kind. A period changed here takes effect on the next tick,
/// with no restart.
pub const TPDO_INTERVAL_MS: u16 = 0x3040;

// --- overpressure relief ---------------------------------------------------

/// Overpressure relief enabled. `uint8`, read/write. At most one loop per node.
///
/// # The one decision a node makes for itself
///
/// A closed volume being heated keeps rising in pressure with nobody commanding anything, and
/// waiting for the master to notice is the wrong dependency for that failure. A node configured
/// with a relief loop watches one sensor slot and, when it goes above the threshold, pulses one
/// valve open for a fixed time, then closes it and lets the reading settle before deciding again.
///
/// Relief outranks everything: the commanded position, the input clamp, and both heartbeat
/// fallback stages. There is no link state in which the right answer to "this vessel is over
/// pressure" is to leave the valve where it was, and in particular it stays active through
/// fallback stage A — a brief comms dropout is exactly when nobody else is watching the tank. It
/// is not tied to the fallback machinery at all; the state machine has no notion of the link.
///
/// A slot with no valid reading *inhibits* relief rather than triggering it — venting a vehicle
/// because a sensor cable fell off would be its own incident. That state is visible at
/// [`RELIEF_STATE`].
pub const RELIEF_ENABLED: u16 = 0x3050;

/// Index of the valve to open, or [`NO_INDEX`] for none. `uint8`, read/write.
///
/// An armed loop pointing at a valve that is not fitted is rejected on save, rather than looking
/// configured while quietly doing nothing.
pub const RELIEF_VALVE: u16 = 0x3051;

/// Index of the sensor slot to watch. `uint8`, read/write.
pub const RELIEF_SENSOR: u16 = 0x3052;

/// Open when the watched slot reads strictly above this, **in that slot's own unit**. `int16`,
/// read/write.
///
/// The same number that goes out at [`SENSOR_VALUE`], so no conversion sits between the sensor
/// and the decision: 6000 is 60 bar for a slot reporting centibar. The default is `i16::MAX`,
/// which is unreachable, so a node that has never been configured for relief cannot start venting
/// because some unrelated slot reads high.
pub const RELIEF_THRESHOLD: u16 = 0x3053;

/// How far to open while relieving, promille. `uint16`, read/write.
pub const RELIEF_POSITION: u16 = 0x3054;

/// How long to hold the valve open, milliseconds. `uint16`, read/write.
///
/// Must be long enough for the valve to actually reach the relief position: a servo needs its
/// full [`VALVE_TRAVEL_MS`] first, which is why a relief valve is normally a solenoid. The
/// firmware warns at boot if that looks wrong.
pub const RELIEF_PULSE_MS: u16 = 0x3055;

/// Settling time after a pulse before the threshold is looked at again, milliseconds. `uint16`,
/// read/write.
///
/// Without it, the lag between valve and sensor would make a single decision dump the whole
/// vessel.
pub const RELIEF_COOLDOWN_MS: u16 = 0x3056;

// --- clock/direction steppers ----------------------------------------------
//
// A node may carry up to two stepper actuators (Nanotec PD2-C, or any other driver taking a step
// clock and a direction level). Every object in this block is a 2-entry array, one per actuator.
// On rev2 the high current output software PWM was moved to TIM5 to free TIM2, whose CH3/CH4 are
// the only timer channels the board has left on pins it can reach.
//
// The pinout depends on how many are fitted, and is fixed at build time (pin muxing happens long
// before any configuration is read):
//
//   one actuator          PA2 step, PA3 direction         (COM4 / COM3)
//   two (`dual-stepper`)  PA2 step 0, PA3 step 1, PC10 direction 0, PA5 direction 1
//
// Both step clocks are channels of one timer, so *while both are moving* they move at the same
// rate — the lower of the two planned rates. Targets, step counters and directions are fully
// independent, an actuator that arrives stops on its own, and whenever only one is moving it runs
// at its own planned rate. A config mapping actuator 1 on a firmware built without `dual-stepper`
// is a build mistake, not a bus one: the node logs an error at boot and that actuator never moves.
//
// The master does not have to know. A stepper occupies an ordinary valve slot with kind 3
// ([`VALVE_KIND`]) and is commanded exactly like a servo through [`VALVE_COMMANDED`] and friends.
// What differs underneath:
//
// - No high current output. Its [`VALVE_POWER_HCO`]/[`VALVE_SIGNAL_HCO`] are both "none" and it
//   never appears in [`HCO_OWNER`]. [`VALVE_CURRENT`] reads 0 for it — the shunts only cover the
//   outputs — so stall detection ([`VALVE_STALL_MA`]) is not available and must stay at 0.
// - [`VALVE_MEASURED`] is exact. The pulses are counted in hardware, so the reported position is
//   measured rather than integrated from [`VALVE_TRAVEL_MS`], which is ignored for a stepper.
// - The unpowered flag is accepted and ignored. ENABLE is strapped to 5 V, so the motor holds
//   torque whenever it has power. The measured word never has bit 15 set for a stepper, and the
//   fallback unpower flags ([`FALLBACK_A_UNPOWER`]/[`FALLBACK_B_UNPOWER`]) do nothing — the
//   firmware warns at boot if they are set.
//
// Homing is [`STEPPER_POSITION`].

/// Index of the valve slot each actuator is, or [`NO_INDEX`]. `uint8[2]`, read/write.
///
/// That slot's [`VALVE_KIND`] must be 3 (stepper), and the two actuators may not name the same
/// slot. Both directions are checked on save, because a mismatch would either accept commands
/// that move nothing or plan moves for a valve that drives an output pair.
pub const STEPPER_VALVE: u16 = 0x3060;

/// Step count at 0 promille. `int32[2]`, read/write.
pub const STEPPER_CLOSED_STEPS: u16 = 0x3061;

/// Step count at 1000 promille. `int32[2]`, read/write.
///
/// May be below [`STEPPER_CLOSED_STEPS`]: the sign of the difference is what picks the direction
/// of rotation, so a reversed actuator is expressed by swapping the endpoints rather than by a
/// separate invert flag. Equal endpoints are rejected on save — the actuator could never move.
pub const STEPPER_OPEN_STEPS: u16 = 0x3062;

/// Traverse speed, steps per second: the ceiling the ramp accelerates toward. `uint32[2]`,
/// read/write.
///
/// Clamped to 20 kHz, well inside the PD2-C's 1 MHz limit — the update interrupt runs once per
/// step, and the period has to stay long enough to give a direction change the 35 µs the driver
/// wants to settle.
pub const STEPPER_MAX_HZ: u16 = 0x3063;

/// Pull-in rate, steps per second. `uint32[2]`, read/write.
///
/// The speed the motor can start *and* stop at without losing steps, which for a 42 mm frame is a
/// few hundred steps per second. Every move begins here and the braking curve never falls below
/// it, so the hard stop on arrival costs nothing. Zero is rejected on save: it means "never
/// start", not "disabled".
pub const STEPPER_START_HZ: u16 = 0x3064;

/// Ramp rate, steps per second squared. `uint32[2]`, read/write.
///
/// 0 is legal and means no ramp at all: every move runs the whole way at the pull-in rate, which
/// is safe but slow. The firmware says so at boot.
pub const STEPPER_ACCEL_HZ_PER_S: u16 = 0x3065;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_sentinels_cannot_collide_with_real_values() {
        // A sensor reading is a signed count of its unit; the invalid marker has to be a value no
        // calibration can legitimately produce, and saturation stops one line short of it.
        assert_eq!(SENSOR_INVALID, i16::MIN);
        assert_eq!(RAW_INVALID, u16::MAX);
        // No index domain on this board is anywhere near 255 entries.
        assert_eq!(NO_INDEX, 0xFF);
    }

    #[test]
    fn the_storage_signatures_are_the_ascii_canopen_asks_for() {
        assert_eq!(SIGNATURE_SAVE.to_le_bytes(), *b"save");
        assert_eq!(SIGNATURE_LOAD.to_le_bytes(), *b"load");
    }

    /// The sub-index a master polls is the discriminant plus one, so a reordering is a silent
    /// protocol break rather than a compile error.
    #[test]
    fn the_error_counter_order_is_pinned() {
        assert_eq!(ErrorCounter::ALL.len(), NUM_ERROR_COUNTERS);
        for (index, counter) in ErrorCounter::ALL.iter().enumerate() {
            assert_eq!(*counter as usize, index, "ALL must stay in discriminant order");
            assert_eq!(counter.sub() as usize, index + 1);
            assert_eq!(ErrorCounter::from_sub(counter.sub()), Some(*counter));
        }
        // Sub 0 is the array length in CANopen, never a counter.
        assert_eq!(ErrorCounter::from_sub(0), None);
        assert_eq!(ErrorCounter::from_sub(NUM_ERROR_COUNTERS as u8 + 1), None);
    }

    /// Indices are the wire, so a duplicate or a typo'd digit is a silent aliasing bug rather
    /// than a compile error.
    #[test]
    fn every_index_is_distinct() {
        let all = [
            STORE_PARAMETERS,
            RESTORE_DEFAULTS,
            HEARTBEAT_PERIOD,
            RAW_ADC_BUS0,
            RAW_ADC_BUS1,
            I2C_PRESENT,
            I2C_SWEEPS,
            SENSOR_VALUE,
            SENSOR_UNIT,
            RAW_ENCODER,
            VALVE_COMMANDED,
            VALVE_TARGET,
            VALVE_MEASURED,
            VALVE_STATUS,
            VALVE_CURRENT,
            RELIEF_STATE,
            HCO_DIGITAL,
            HCO_PWM_US,
            HCO_OWNER,
            LEDS,
            RAW_DEBUG_MODE,
            LINK_STATE,
            MS_SINCE_HEARTBEAT,
            RAIL_CURRENT,
            RAIL_VOLTAGE,
            ERROR_COUNTERS,
            MASTER_NODE_ID,
            FALLBACK_A_MS,
            FALLBACK_B_MS,
            FALLBACK_A_POSITION,
            FALLBACK_B_POSITION,
            FALLBACK_A_UNPOWER,
            FALLBACK_B_UNPOWER,
            FALLBACK_ENABLED,
            VALVE_KIND,
            VALVE_POWER_HCO,
            VALVE_SIGNAL_HCO,
            VALVE_CLOSED_US,
            VALVE_OPEN_US,
            VALVE_TRAVEL_MS,
            VALVE_STALL_MA,
            VALVE_STALL_MS,
            VALVE_SETTLE_MS,
            VALVE_MIN_PROMILLE,
            VALVE_MAX_PROMILLE,
            VALVE_POSITION_SENSOR,
            SENSOR_BUS,
            SENSOR_AMPLIFIER,
            SENSOR_KIND,
            SENSOR_OFFSET,
            SENSOR_SLOPE,
            SENSOR_UNIT_CFG,
            SENSOR_CONSTANT,
            SENSOR_PDO_CHANNEL,
            SENSOR_INTERVAL_MS,
            SCAN_INTERVAL_MS,
            TPDO_INTERVAL_MS,
            RELIEF_ENABLED,
            RELIEF_VALVE,
            RELIEF_SENSOR,
            RELIEF_THRESHOLD,
            RELIEF_POSITION,
            RELIEF_PULSE_MS,
            RELIEF_COOLDOWN_MS,
            STEPPER_POSITION,
            STEPPER_VALVE,
            STEPPER_CLOSED_STEPS,
            STEPPER_OPEN_STEPS,
            STEPPER_MAX_HZ,
            STEPPER_START_HZ,
            STEPPER_ACCEL_HZ_PER_S,
        ];
        let mut sorted = all;
        sorted.sort_unstable();
        for pair in sorted.windows(2) {
            assert_ne!(pair[0], pair[1], "two objects share index {:#06x}", pair[0]);
        }
    }
}
